# Generated by Django 5.0.3 on 2024-03-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shady', max_length=255, unique=True)),
                ('api_key', models.CharField(default='api-key-123', max_length=1055, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_amount', models.DecimalField(decimal_places=2, default='3.00', max_digits=15)),
                ('fiat_currency', models.CharField(default='usd', max_length=50)),
                ('crypto_currency', models.CharField(default='ADA', max_length=50)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.CharField(max_length=200, unique=True)),
                ('currency', models.CharField(default='ADA', max_length=50)),
            ],
        ),
    ]
