# Generated by Django 5.0.3 on 2024-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0008_alter_mining_quantity_mined_alter_mining_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='mineral_extracted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
